import argparse
import random

def generate_swf(num_jobs, job_id_start,
                submit_time_start, submit_time_step,
                wait_time_default,
                run_time_min, run_time_max,
                min_procs, max_procs,
                avg_cpu_frac,
                mem_min_kb, mem_max_kb,
                status_choices,
                user_id_min, user_id_max,
                group_id_min, group_id_max,
                executable_min, executable_max,
                queue_default, partition_default,
                preceding_job_default,
                think_time_default,
                output_file):

    submit_time = submit_time_start
    with open(output_file, 'w') as f:
        f.write("; Synthetic SWF workload generated by script\n")
        f.write("; Fields:\n")
        f.write("; 1.JobID 2.SubmitTime 3.WaitTime 4.RunTime 5.NumAllocatedProcessors\n")
        f.write("; 6.AvgCPUTimeUsed 7.UsedMemory 8.RequestedProcessors 9.RequestedTime\n")
        f.write("; 10.RequestedMemory 11.Status 12.UserID 13.GroupID 14.Executable\n")
        f.write("; 15.Queue 16.Partition 17.PrecedingJob 18.ThinkTime\n")

        for i in range(num_jobs):
            job_id = job_id_start + i
            wait_time = wait_time_default
            run_time = random.randint(run_time_min, run_time_max)
            num_procs = random.randint(min_procs, max_procs)
            avg_cpu_time = run_time * avg_cpu_frac
            used_memory = random.randint(mem_min_kb, mem_max_kb)
            requested_procs = num_procs
            requested_time = run_time
            requested_memory = used_memory
            status = random.choice(status_choices)
            user_id = random.randint(user_id_min, user_id_max)
            group_id = random.randint(group_id_min, group_id_max)
            executable = random.randint(executable_min, executable_max)
            queue = queue_default
            partition = partition_default
            preceding_job = preceding_job_default
            think_time = think_time_default

            line = f"{job_id} {submit_time} {wait_time} {run_time} {num_procs} " \
                    f"{avg_cpu_time:.2f} {used_memory} {requested_procs} {requested_time} {requested_memory} " \
                    f"{status} {user_id} {group_id} {executable} {queue} {partition} {preceding_job} {think_time}\n"
            f.write(line)

            submit_time += submit_time_step

    print(f"Generated {num_jobs} jobs to {output_file}")

if __name__ == "__main__":
    parser = argparse.ArgumentParser(description="Generate a customizable synthetic SWF workload file.")

    parser.add_argument("--num_jobs", type=int, default=100, help="Number of jobs to generate")
    parser.add_argument("--job_id_start", type=int, default=1, help="Starting job ID")
    parser.add_argument("--submit_time_start", type=int, default=0, help="Submit time for first job")
    parser.add_argument("--submit_time_step", type=int, default=10, help="Increment of submit time between jobs")
    parser.add_argument("--wait_time_default", type=int, default=0, help="Default wait time for all jobs")
    parser.add_argument("--run_time_min", type=int, default=10, help="Minimum run time")
    parser.add_argument("--run_time_max", type=int, default=1000, help="Maximum run time")
    parser.add_argument("--min_procs", type=int, default=1, help="Minimum processors per job")
    parser.add_argument("--max_procs", type=int, default=16, help="Maximum processors per job")
    parser.add_argument("--avg_cpu_frac", type=float, default=0.9, help="Fraction of runtime that is CPU time")
    parser.add_argument("--mem_min_kb", type=int, default=100000, help="Minimum memory used (KB)")
    parser.add_argument("--mem_max_kb", type=int, default=1000000, help="Maximum memory used (KB)")
    parser.add_argument("--status_choices", nargs='+', type=int, default=[1], help="Possible job statuses (e.g. 0,1,5)")
    parser.add_argument("--user_id_min", type=int, default=1, help="Minimum user ID")
    parser.add_argument("--user_id_max", type=int, default=10, help="Maximum user ID")
    parser.add_argument("--group_id_min", type=int, default=1, help="Minimum group ID")
    parser.add_argument("--group_id_max", type=int, default=10, help="Maximum group ID")
    parser.add_argument("--executable_min", type=int, default=1, help="Minimum executable ID")
    parser.add_argument("--executable_max", type=int, default=5, help="Maximum executable ID")
    parser.add_argument("--queue_default", type=int, default=1, help="Queue number")
    parser.add_argument("--partition_default", type=int, default=1, help="Partition number")
    parser.add_argument("--preceding_job_default", type=int, default=-1, help="Preceding job ID")
    parser.add_argument("--think_time_default", type=int, default=0, help="Think time after preceding job (seconds)")
    parser.add_argument("--output", type=str, default="synthetic_workload.swf", help="Output SWF file")

    args = parser.parse_args()

    generate_swf(
        num_jobs=args.num_jobs,
        job_id_start=args.job_id_start,
        submit_time_start=args.submit_time_start,
        submit_time_step=args.submit_time_step,
        wait_time_default=args.wait_time_default,
        run_time_min=args.run_time_min,
        run_time_max=args.run_time_max,
        min_procs=args.min_procs,
        max_procs=args.max_procs,
        avg_cpu_frac=args.avg_cpu_frac,
        mem_min_kb=args.mem_min_kb,
        mem_max_kb=args.mem_max_kb,
        status_choices=args.status_choices,
        user_id_min=args.user_id_min,
        user_id_max=args.user_id_max,
        group_id_min=args.group_id_min,
        group_id_max=args.group_id_max,
        executable_min=args.executable_min,
        executable_max=args.executable_max,
        queue_default=args.queue_default,
        partition_default=args.partition_default,
        preceding_job_default=args.preceding_job_default,
        think_time_default=args.think_time_default,
        output_file=args.output
    )
